console.log("_".repeat(80));
console.log(6 + 2);
console.log("_".repeat(80));
console.log(4 * 2);
console.log("_".repeat(80));
console.log(16 - 8);
console.log("_".repeat(80));
console.log(16 / 2);
console.log("_".repeat(80));
export {};
